version: '3.6'

services:
  neo4j:
    image: neo4j:5
    ports:
      - '7474:7474'
      - '7687:7687'
    volumes:
      - './neo4j_conf:/var/lib/neo4j/conf'
      - './neo4j_data:/var/lib/neo4j/data'
      - './neo4j_import:/var/lib/neo4j/import'
      - './neo4j_logs:/var/lib/neo4j/logs'
      - './neo4j_plugins:/var/lib/neo4j/plugins'
    restart: always
